spring:
  application:
    name: portfolio-api

  datasource:
    url: ${DB_URL}
    username: portfolio_projeto_user
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

services:
  member-api:
    url: http://localhost:8080